language: python
python:
    - 3.5
    - 3.6
services:
    - docker
before_install:
    - docker run --name arango -d -p 8529:8529 -e ARANGO_NO_AUTH=1 arangodb/arangodb
install:
    - pip install pylint pytest pytest-cov
    - pip install .
script:
    - pylint -E eve_arango
    - pytest -svv --cov=eve_arango
